name: 'Tracer Action'
description: Tracer description
author: FastCI Tracer
inputs:
  jfrog_user_writer:
    description: "JFrog User Writer"
    required: true
  jfrog_password_writer:
    description: "JFrog Password Writer"
    required: true
  fastci_otel_endpoint:
    description: "OpenTelemetry Endpoint that will receive the traces"
    required: true
  fastci_otel_token:
    description: "OpenTelemetry token"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Expose GitHub Runtime
      uses: fastci-dev/ghaction-github-runtime@master
     
    - name: Start Fastci Tracer Action
      run: |
        # Download files in parallel using wget
        wget -q -O tracer-bin https://github.com/fastci-dev/tracer-bin/releases/download/main/tracer-bin
        
        # Wait for all background processes to complete
        wait

        # Start tracer
        sudo -E ./tracer-bin &
      shell: bash
