name: 'Tracer Action'
description: Tracer description
author: FastCI Tracer
inputs:
  input1:
    description: Description of input 1
    required: false
  input2:
    description: Description of input 2
    required: false
    default: "default value"
  # Add more inputs as needed

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start Fastci Tracer Action
      run: |
        curl -O -L https://raw.githubusercontent.com/fastci-dev/tracer-bin/main/tracer-bin
        chmod +x tracer-bin
        sudo -E SERVER_HOST=63.34.12.1 SERVER_PORT=50052 ./tracer-bin &
        sleep 5
      shell: bash
