name: 'Tracer Action'
description: Tracer description
author: FastCI Tracer
inputs:
  input1:
    description: Description of input 1
    required: false
  input2:
    description: Description of input 2
    required: false
    default: "default value"
  # Add more inputs as needed

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Expose GitHub Runtime
      uses: fastci-dev/ghaction-github-runtime@master
      
    - name: Define and export docker function
      shell: bash
      run: |
        echo test
        #echo 'FASTCI=docker() { bash /home/runner/work/github-actions-tests/github-actions-tests/docker-build-alias.sh "$@";}' >> $GITHUB_ENV
        
    - name: Start Fastci Tracer Action
      run: |
        # Download files in parallel using wget
        wget -q -O tracer-bin https://github.com/fastci-dev/tracer-bin/releases/download/main/tracer-bin &
        wget -q -O docker.sh https://github.com/fastci-dev/tracer-bin/releases/download/main/docker.sh &
        
        # Wait for all background processes to complete
        wait

        # Set permissions and move docker.sh to the desired location
        chmod +x tracer-bin docker.sh
        mkdir -p /home/runner/.local/bin || echo "Could not create docker directory"
        mv docker.sh /home/runner/.local/bin/docker  || true

        # Export secrets as environment variables
        export JFROG_USER_WRITER=${{ secrets.JFROG_USER_WRITER }}
        export JFROG_PASSWORD_WRITER=${{ secrets.JFROG_PASSWORD_WRITER }}

        # Start tracer
        sudo -E SERVER_HOST=52.23.138.136 SERVER_PORT=50051 JFROG_USER_WRITER=${JFROG_USER_WRITER} JFROG_PASSWORD_WRITER=${JFROG_PASSWORD_WRITER} ./tracer-bin &
      shell: bash
