name: 'Tracer Action'
description: Tracer description
author: FastCI Tracer
inputs:
  jfrog_user_writer:
    description: "JFrog User Writer"
    required: true
  jfrog_password_writer:
    description: "JFrog Password Writer"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Expose GitHub Runtime
      uses: fastci-dev/ghaction-github-runtime@master

    - name: Install Buildx
      run: docker buildx create --use --name mybuilder --driver docker-container

              
    - name: Start Fastci Tracer Action
      run: |
        # Download files in parallel using wget
        wget -q -O tracer-bin https://github.com/fastci-dev/tracer-bin/releases/download/main/tracer-bin &
        wget -q -O docker.sh https://github.com/fastci-dev/tracer-bin/releases/download/main/docker.sh &
        
        # Wait for all background processes to complete
        wait

        # Set permissions and move docker.sh to the desired location
        chmod +x tracer-bin docker.sh
        mkdir -p /home/runner/.local/bin || echo "Could not create docker directory"
        mv docker.sh /home/runner/.local/bin/docker  || true

        # Start tracer
        sudo -E SERVER_HOST=52.23.138.136 SERVER_PORT=50051 ./tracer-bin &
      shell: bash
