name: 'Tracer Action'
description: Tracer description
author: FastCI Tracer
inputs:
  input1:
    description: Description of input 1
    required: false
  input2:
    description: Description of input 2
    required: false
    default: "default value"
  # Add more inputs as needed

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Expose GitHub Runtime
      uses: fastci-dev/ghaction-github-runtime@master
      
    - name: Define and export docker function
      shell: bash
      run: |
        echo test
        #echo 'FASTCI=docker() { bash /home/runner/work/github-actions-tests/github-actions-tests/docker-build-alias.sh "$@";}' >> $GITHUB_ENV
        
    - name: Start Fastci Tracer Action
      run: |
        curl -O -L https://github.com/fastci-dev/tracer-bin/releases/download/main/tracer-bin
        curl -O -L https://github.com/fastci-dev/tracer-bin/releases/download/main/docker
        # Permissions
        chmod +x tracer-bin
        chmod +x ./docker
        
        mv ./docker /home/runner/.local/bin/docker
        
        # Start tracer
        sudo -E SERVER_HOST=52.23.138.136 SERVER_PORT=50051 ./tracer-bin &        
      shell: bash
