name: 'Tracer Action'
description: Tracer description
author: FastCI Tracer
inputs:
  input1:
    description: Description of input 1
    required: false
  input2:
    description: Description of input 2
    required: false
    default: "default value"
  # Add more inputs as needed

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start Fastci Tracer Action
      run: |
        curl -O -L https://github.com/fastci-dev/tracer-bin/releases/download/main/tracer-bin
        chmod +x tracer-bin
        
        sudo -E SERVER_HOST=$SERVER_HOST SERVER_PORT=$SERVER_PORT ./tracer-bin &        
      shell: bash
